import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;

import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Test suite for the Anagram class.
 * <p>
 * The provided test suite is correct and complete. You should not need to modify it. However, you
 * should understand it. You will need to augment or write test suites for later MPs.
 *
 * @see <a href="https://cs125.cs.illinois.edu/MP/2/">MP2 Documentation</a>
 */
public class AnagramTest {

    /** Timeout for simple tests. */
    private static final int SIMPLE_TEST_TIMEOUT = 100;

    @Test(timeOut = SIMPLE_TEST_TIMEOUT)
    public void testAreStrictAnagramsWithGoodInputs() {
        Assert.assertTrue(Anagram.areStrictAnagrams("", ""), "Incorrect result for empty strings");
        Assert.assertTrue(Anagram.areStrictAnagrams("A", "A"), "Incorrect result for identical strings");
        Assert.assertFalse(Anagram.areStrictAnagrams("A", "a"), "Incorrect result for different cased strings");
        Assert.assertTrue(Anagram.areStrictAnagrams("ABA", "BAA"), "Incorrect result for simple anagrams");
        Assert.assertTrue(Anagram.areStrictAnagrams("ABA", "B.A.A"), "Incorrect result for simple anagrams with added punctuation");
        Assert.assertTrue(Anagram.areStrictAnagrams("A-B-A", "B A A"), "Incorrect result for simple anagrams with added punctuation or whitespace");
        Assert.assertFalse(Anagram.areStrictAnagrams("ABA", "ABAABA"), "Incorrect result for simple anagrams different character counts");
        Assert.assertFalse(Anagram.areStrictAnagrams("ABA", "ABC"), "Incorrect result for single different character");
    }

    @Test(timeOut = SIMPLE_TEST_TIMEOUT)
    public void testAreStrictAnagramsWithBadInputs() {
        Assert.assertFalse(Anagram.areStrictAnagrams(null, ""), "Incorrect result for null inputs");
        Assert.assertFalse(Anagram.areStrictAnagrams("", null), "Incorrect result for null inputs");
        Assert.assertFalse(Anagram.areStrictAnagrams(null, null), "Incorrect result for null inputs");
    }

    /**
     * Timeout for grading test. Solution takes 48 ms.
     */
    private static final int GRADING_TEST_TIMEOUT = 960;

    /**
     * Grade with precomputed values.
     */
    @Test(timeOut = GRADING_TEST_TIMEOUT)
    public void gradeAreStrictAnagrams() {
        for (Map.Entry<ArrayList<String>, Boolean> precomputed : PRECOMPUTED_RESULTS.entrySet()) {
            ArrayList<String> input = precomputed.getKey();
            Boolean output = precomputed.getValue();

            Assert.assertEquals(Anagram.areStrictAnagrams(input.get(0), input.get(1)), (boolean) output,
                    "Incorrect result for " + input.get(0) + " and " + input.get(1));
        }
    }

    /**
     * Pre-computed testing values.
     */
    private static final Map<ArrayList<String>, Boolean> PRECOMPUTED_RESULTS =
            new LinkedHashMap<>() {
                {
                    /* BEGIN AUTOGENERATED CODE */
                    put(new ArrayList<>() {
                        {
                            add("nQCPt2vRCw9sWxV1FB2ZSJdrgVeX8BId4jguX5T84QLCzEEwn0IOJofvJ");
                            add("Br!vuF24EXTw0R.nBxPdgO2djCevIVCnJg8z-48f5sjIQ9Q1CtXSZLVwJoW-E");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("nS9FcRKg4IO99FnUxu0yiE4PFQ27bh4Rk1K4znMdDRb3xWs");
                            add("uFcdRd^ 4F4K iQE,90y2nzM9KsgO9R14KInbbS7PhUFxWRx3n4");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("sQTMoMacrGCyxXOV0qd5Xm4506WriPKAVZ");
                            add("PUmW0aX0rBsyOAVO-gQMq4rIxTcK 5ZMXeKX,");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("Sa3m0P9xOlonK7yQ4ufdbeijUb");
                            add("S0,4KdPyn efObiauQ!.bo93 mJl!Ux,.7");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("QxQ5YYTZacG7KP0iPfzxTmEagv3uYjUwgvD");
                            add("avaxgYQgu03TwQjYivPUz7mGZYxPDTfKE5c");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("jowt2yQnwnhvwkm");
                            add("Zvylnk t-,wYotwSwh");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("WmJk5E5S4ZTLoSomkPAEciZWFTvye68pG");
                            add("E4kS^WAGJmZo 8o5 Ty iPkTSv6!-EmcZpF5,LWe");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("TXX6LbR2df1nITp14F");
                            add("R6-1FI1T24!n.PPf-XTabd");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("HBazCYVKygbWbuEgsLGLg5XG8c1ZFpjr0QXPAtFO8LMmQnCLFIwaewibxQ");
                            add("8yBzX0Fm8WEFArfPucbY-ZO5CjILwaxnGwbesVHbQggLpXimlLKGQ1aCQtg");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("kP2PN0M0euuXEPARm5ymh");
                            add("R0E^52-PM^HkePmirw5m0Dyu");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("y3c1efe3YpNuGI9cF4IK1hjAsny4McYCDy3qwgnePDcrGm");
                            add("GP.ciYG3cyW3Kq4wNsryeneg!pf1u19Cme-D4c3AFjMyDchIY");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("duceoIenlxsI8XkdJwDkKmwuEhn5AHZ1cpEF1XcI7ASp3HbVCSOUXclal0");
                            add("7xsmcaK8n!Aled1OlFlSkXkCwu3ILca0nUd6Vp-RwEEuSHHJelcXcZpobI15");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("eCNMODrJdU8TgDBAeVOj6fwzcgipe6ivKUxuEjC9Vvv9RA4p7gZhXuGXEWplavKi");
                            add("8g!MdNexOv6GzVZUhRAuBXQiKD99WCpe7jwJe^7VjpUgdpicvrfla7gTCvAx7E4UWv");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("vjY716ze1oReLK0tzfecKFoPVjdYFWYLAHRCTr2");
                            add("2V7KR,LojYWdejT01SrCFRH^c!L NtfYoFz,3^zBV1PLk");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("EzJkUsuXGHU9mlxDHtfBTqMmvR49XS3fSusvhnDuqMyQQfo");
                            add("Rq3Tyl9GmXtuf4SsuUsq.zf9mBXJoUvvfuEn MkQSDHHMxhDQ");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("AQszA93bCrSVjb6");
                            add("z.3ACssb,rAV,jb6Q9.");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("8QL9IbGYu");
                            add("g8.LUgn.Yb I");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("xM9la2KTUj5oF9Hh");
                            add("2,9M l9.Kj^ToahHU-F.5x");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("XvJgHUTx4afvdNM");
                            add("fHvxJva M.!U!TDN X,4g^^");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("YpsinPnEZruRfuVk1oVzGyJxGZLJttkdxBwy6Luz8zcQnMXew");
                            add("Prz-1Yy.wtRLnexJsZ.xuLwd^xQ8ZJVnuc7oGzEtuBzkMk6ypVif.G");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("57L1KYaq2kYvt1SRa5KkECaB4KSXYOkfsByTyozNLd");
                            add("YClP.KtYfS, 1L.kk-aEvXSVBoyLzY4qNkB5S7^2acKRKaiT");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("gORau9wq");
                            add("!QU AO.WRg 9");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("tAXZ9LiuFHxqQRTdL0Or27HzafYQIDi49PvMMk3o4qwfohatvMeI1d8WYnE");
                            add("9exvWMY^otw7Y9Pqz,nMOLdftFR4QfXq.HhIM,Q8aLR01Iak2 Hio4TEvD zDA3ui");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("x6rZiQjiX3Vlabo5QN8Zr85lfu9ZhXA5Qc5u1BQuc87pk4XapVh6GkUGx");
                            add("XimQ7AU8uVPOZ5QXlk6fG5jbQUiuxu6Khxoa,khV15g9cpQB4GcYuXrlr5");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("jYArCEg1lxJSX5iio7DPZLre7wUUfw9UzgHtjzhIVnnv3Li1zGnMJ2");
                            add("7nfs9Dhi2PvS1gZYJz,L7Cng-UzE!Jj861MxUirIHnGXx^aUVjirRwzwlt");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("uJ2AOTyWOubTfQnZsohIAEPce93aBYR");
                            add("u^!IOc-s-AQoZYh3Y892!bfeNJTYPaObWTEA");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("kBhSt2ChQWVozCTIqwhfmaEMNFRXAk33jalb1Kc37kxt9jRr1SmmY9yv");
                            add("tXjq69KoCm91knhRECEFtyyQSzwExacv3VlM3BzTWSH.amB3hmr1k^RAjr");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("6H6wsJT0PaR8cjBji1PQ0owRNZgd7op6R0weTR");
                            add("d7paBRTJjR1sZiP0gpjR80HoeR6Nc6owQ6Tw0w");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("KSz4BUXxPWHKwhKlotbJoxQDUSaF");
                            add("jxH,zlUoQO.aB4P ttZUxwKD,!eSbHSFk");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("bu4kdtHQDkecBPpF5");
                            add("kHFp5u cQBD -^-BK.4tPd-E");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("0L8NL9E6xpYwTjPcts4OCP8xmE78DF0KevtUaLUuOPTOCBJ4kDYC");
                            add("6PDC7ULLTECPpUEOmxD0Px0ct-8Bw^J8O,s^t4kNKTYujOv4,98F!LeYC.a");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("x0vp5Lpt1qc2oJUm5siVGjMuF85liJrMF0SEBTVIjw59QdXLndlhUVHX5EnNn");
                            add("Isdp50SQHVEUJEt.52^vh9NUM 8VldXni5X^GLVwixTquJ!Mrcm1Blp5o5nLj0FjFn");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("MfSTUcoW7KLSzjrT1AgQxjIZ9D");
                            add("IDfTgKWA9SOc7AjlQuQj!rxoMSZ");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("hQStKdEv2ibZEIEgZCfsdvFPclDylxkCgGmfRtnz3YOfuEu3c37iLQmIqQk9");
                            add("EB7cCgQqlntiL3kvfY9ExDmCb3ZmIyluZPNhdSzKtdEO9WIigs3f2gkQsvRF");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("mG6Gghuvug7C48PrB7HTT1Z5Crw4nmuDiTY96pDhW0KNRixH6VHMY");
                            add("u4YT66PDDZgY8rGMWH65GNru9KHRHMC7BuCnhdCgiwvV71T4T0pxi");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("yWf4IAnuSIS0lDiRfqHBtNlNv0d8l0RweEjwDERygaZ4zuh0CCBhC");
                            add("SDheuRDIli8CuwNfSqCyg!NHCBjZaW00lvzR4EtB40yhd.f REwAI0lN");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("eSAYykaBL6MbJBrq4ukz1T65cNfm");
                            add("1.z-lMkuS546rqaJ e^.BTYB6N.-fkm!cyAb");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("hvVcZPzjN0TGuVZaL");
                            add(", ahT.,.VZ,ujV!N PvcLGZz0");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("JQ7EQHfAmmABjghSsvXECG8IMc0cX00zleD5");
                            add("5D8zHfXh EAICm,QcE. 70MQAB0vjmCGGXe0JslS");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("hYiK1lySWcWrg0");
                            add("hy YKriW,CgWl01S");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("LhyDKylcFKCQGW2vQAxz1e3H8xkuydUdPnU8EMonshYnj8m");
                            add("oML!hnhQKxx2cnvkAdYUd^ul^8syFH3P..EDyK1nQmGW8jU,yCe^8z");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("z9xfX8RyQIxiNTiiptJB5i5tNO6GT95lfSZ7nrMv");
                            add("BT5xln57QJ8y6zXOx1RMBtirTXdIvfiNPt5xzA9i");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("E7sSEDDyXjyfo");
                            add("DxsDjf-7EEo! ysy ");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("VOkewTjm6UN4W16zJunvNpP8uhIPigINIiPOcXswc");
                            add("vkTs6iiuu^xOO16VIn8JPcNpNch4AmjwgewPIWfIpN");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("Fzbs40qGuPWWkpNtGBxLWQZRVKRBNlo2y8eDVXznyEJrephdZQ0hvNLmk");
                            add("JltxsBKrdGZK8.PW4VNh2WWX0RmBDdrVGpZuvezHQLnheq-qLy0zyVb2E-Vl");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("ranVLTTjmT5ty6qpvUw6uh5hVOeeFsKB9wI3gmiXF4SwQiFS1e2madGnRgeIO");
                            add("mLS^nmBn3TOKh^6O!FdXsTyVeIeU5G.eeT9R6pt1hgIwaSF4Q-vVFgmjqw2rwai5ui");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("gVlQUwqVvj6O6XE0fbtxFKYxYH");
                            add("YLk.XuYx6T6xEwVqj0fHVovgqbf");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("lGkJk8ZzE");
                            add("kJjZ 4 E8,^T-g");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("A1SQAeP5ZXjAW9X6OyIMm9UG3rJtT7dR4roiqgCTCdsZfd1k");
                            add("6yAWieOZMmXjJrL,Qg459UrqR93d1ATktCTIdPd1Cs.ASfZo7X");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("99l3NfttEK3JtdOpW5JH");
                            add("3JS- EONdHK.YW9^i5L!p9Jt5.! ");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("jdrn6I0dsFZm67p");
                            add("j6Zps.r,nm!d.6d07I-,F");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("qrP5DHz4qciMfOiwAY");
                            add("qAqYcw45!Pi!H!Drm i,fOz");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("9NiXmG98PEq5R");
                            add("R^y!^q9,i,EY9X N6.mP");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("QawPzx1P4gRXfS8zw5fbpNQNgt8Qh3wBPZ0MgJPw");
                            add(".wZ...SxpN8ggXJgQ83wPbQhPtRNQw,P4fmaB1^zPw5zf0 ");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("SHRV04rXp01ESpOpq3jgDMeRF1KD");
                            add(",3HDpDRRE,0Xs1Mrejp0p41kFO-sqVg");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("2A2CinnlF2RIakAlmppbCTG");
                            add("kIFaC2mibG7ARnp2lnCTlAf");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("nBn6oTfXXzrtJMYC5rYOu1QuQ6WBZ2qEpG6xXz");
                            add("^-x 1prB6CXzquW^6zM6TuYXYOBJG ZXon2E5nQQtr f");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("jsKMdBYYZAoMcc5SmqOYyWglFGU7EMahzQipfxNKvEue50OEbFk4Twz");
                            add("heUvWZjFMK5zikOE5S4cs7EcqAywqF0NYTaM^gBM!oQpE.fbOduYmKGxYz");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("ziyFFJtqIyiZbdgbu4HPDVj0xmh6mM9raJVbemepP5Dowc");
                            add("J0JVRejPoo4bMagewx!mGa,6!u^^FqBDHdPz9yyk-t,mD IcpbErbZ");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("LS1w0St2wb02");
                            add("L!0tS12w0w2Sb");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("TuBQBn6bOakGVPBNXw5zbY1a");
                            add("BBXunzQVPGkw6bT15a. bbPaNY");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("FlCgJC4LiDQucQXPVE0qJNyc9itc4QPIyTym");
                            add("yIiTQmy4PgNuyccEc9lVJ4tXQP0JCQDQLFCi");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("UxE17nzcCxuUTKwyUcdUPBKBEAtGog0gQ527DLcuTDe1r7t6dHWGw46cT30gmNeE");
                            add("ccT^z-eUtudr,5Tt1HBPxAT6EwUcdgn1KwCUgeWoG4 N7d37Egx,Gm2UEQu76,cK0LyDB0, ");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("efNWk3SLajCT4jTpRbQdq4meakS3Rs3BDvTdFrPRDLHAvn");
                            add("e!qSsmLC4aHTQ4FfdN3-!bSpLj.DBRA!3!.arWnRvRvTkjdekP3TD");
                        }
                    }, true);
                    /* END AUTOGENERATED CODE */
                }
            };
}
