import java.util.LinkedHashMap;
import java.util.Map;

import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Test suite for the CheckPassword class.
 * <p>
 * The provided test suite is correct and complete. You should not need to modify it. However, you
 * should understand it. You will need to augment or write test suites for later MPs.
 *
 * @see <a href="https://cs125.cs.illinois.edu/MP/2/">MP2 Documentation</a>
 */
public class CheckPasswordTest {

    /** Timeout for simple tests. */
    private static final int SIMPLE_TEST_TIMEOUT = 100;

    @Test(timeOut = SIMPLE_TEST_TIMEOUT)
    public void testCheckAPasswordWithGoodInputs() {
        Assert.assertFalse(CheckPassword.checkAPassword("", 1, 0, 0, 0),
                "Password length checking not working");
        Assert.assertTrue(CheckPassword.checkAPassword("Chuchu", 3, 0, 0, 0),
                "Password length checking not working");
        Assert.assertTrue(CheckPassword.checkAPassword("ChuChu", 3, 2, 0, 0),
                "Password capital letter checking not working");
        Assert.assertFalse(CheckPassword.checkAPassword("ChuChu", 3, 3, 0, 0),
                "Password capital letter checking not working");
        Assert.assertFalse(CheckPassword.checkAPassword("ChuChu", 3, 3, 1, 0),
                "Password number checking not working");
        Assert.assertTrue(CheckPassword.checkAPassword("ChuChu10", 3, 2, 1, 0),
                "Password number checking not working");
        Assert.assertFalse(CheckPassword.checkAPassword("ChuChu10", 3, 3, 1, 1),
                "Password special character checking not working");
        Assert.assertTrue(CheckPassword.checkAPassword("ChuChu10_*", 3, 2, 1, 2),
                "Password special character checking not working");
    }

    /**
     * Timeout for our grading test. Solution takes 54 ms.
     */
    private static final int GRADING_TEST_TIMEOUT = 1080;

    /**
     * Grade with precomputed values.
     */
    @Test(timeOut = GRADING_TEST_TIMEOUT)
    public void gradeCheckAPassword() {
        for (Map.Entry<CheckPasswordInput, Boolean> precomputed : PRECOMPUTED_RESULTS.entrySet()) {
            CheckPasswordInput input = precomputed.getKey();
            Boolean output = precomputed.getValue();

            Assert.assertEquals(CheckPassword.checkAPassword(input.password,
                    input.minLength, input.minCapitalLetter, input.minNumber, input.minSpecial), (boolean) output,
                    "Incorrect result for " + input);
        }
    }

    public static class CheckPasswordInput {
        /** Password to check. */
        final String password;

        /** Minimum password length. */
        final int minLength;

        /** Minimum password letter count. */
        final int minCapitalLetter;

        /** Minimum password number count.*/
        final int minNumber;

        /** Minimum password special character count. */
        final int minSpecial;

        @Override
        public String toString() {
            return "CheckPasswordInput{" +
                    "password='" + password + '\'' +
                    ", minLength=" + minLength +
                    ", minCapitalLetter=" + minCapitalLetter +
                    ", minNumber=" + minNumber +
                    ", minSpecial=" + minSpecial +
                    '}';
        }

        public CheckPasswordInput(String password, int minLength, int minCapitalLetter, int minNumber, int minSpecial) {
            this.password = password;
            this.minLength = minLength;
            this.minCapitalLetter = minCapitalLetter;
            this.minNumber = minNumber;
            this.minSpecial = minSpecial;
        }
    }
    /**
     * Pre-computed testing values.
     */
    private static final Map<CheckPasswordInput, Boolean> PRECOMPUTED_RESULTS =
            new LinkedHashMap<>() {
                {
                    /* BEGIN AUTOGENERATED CODE */
                    put(new CheckPasswordInput("v9VS0^1Y",
                            6, 3, 3, 0), true);
                    put(new CheckPasswordInput("KifPkTNuhcBVrGbV0Uu69aQPv8X_T#vA*eu8Ly3puBJx*FPqRJ9YmmST",
                            56, 28, 7, 4), false);
                    put(new CheckPasswordInput("sRKledvDyvTXYXRHJ0KE3qal1*_$T@HJ!S@2x5X3k2mtKR0MvDs",
                            51, 21, 8, 10), false);
                    put(new CheckPasswordInput("$%Hqp!vON@WjU5y$MzLx6tIamsW2@IPnnwUq3AKYE*Ele_PW2mf",
                            51, 19, 4, 7), true);
                    put(new CheckPasswordInput("_lh_71c4i",
                            9, 0, 2, 0), true);
                    put(new CheckPasswordInput("y@oCMU!koZIbya%wQrQgBowku994oatgXyW$LFAu@X2S@J7ElR_CupEj",
                            56, 19, 3, 7), true);
                    put(new CheckPasswordInput("$y%LZsw_ku@Jj6c7k41rPoq8@TgPpSXJ8lz",
                            35, 9, 9, 5), false);
                    put(new CheckPasswordInput("*iZNBukBpjlYJC7wwm",
                            18, 7, 1, 4), false);
                    put(new CheckPasswordInput("@PnxmhLh",
                            6, 2, 0, 0), true);
                    put(new CheckPasswordInput("b^QJVP5RWJIrKr8KeSmXnUfneEnQ!1mYHDxp%8",
                            38, 18, 4, 6), false);
                    put(new CheckPasswordInput("7@bdgd!8h3^kjB#$4F5^!8^SLKw_0RiGXumN4nzRktRE!tdMw_6SSKO1a",
                            57, 17, 14, 11), false);
                    put(new CheckPasswordInput("NqDTK6NZf0WRBOyyhkQ*On^_pUsulhwrrEAGD_8f!cE^9R$ARWsPi64nG",
                            57, 22, 5, 7), true);
                    put(new CheckPasswordInput("DtvVA*8GIK$LT076r#v$%1RjRKNPNG9US#y0_n_*7Hk8shFHX2a@GgQy*",
                            57, 22, 9, 11), true);
                    put(new CheckPasswordInput("iffenq$Qc",
                            10, 1, 0, 1), false);
                    put(new CheckPasswordInput("%_hN49e%neKGNfOMEeTPYTXisseSXaiZyCeI*3hWNHlO_kzuBEy2uMv",
                            55, 22, 2, 4), true);
                    put(new CheckPasswordInput("v60DxXn3O$7H!uc*YW*ZZ0XmHiB5yW0$2rqC",
                            36, 14, 8, 5), false);
                    put(new CheckPasswordInput("AD@nE8tlij317l8VNrd7SAkzlMY*tzxFs!8E@ccKttqOob1M#r",
                            50, 13, 7, 3), true);
                    put(new CheckPasswordInput("MgsdEEQ70EtXPPWy7OkkQ%lL5dCXIJNN7Uado@74pYxX7ufPKdnGnpTlCC%rZ1",
                            62, 28, 10, 3), false);
                    put(new CheckPasswordInput("wb%9!lnl7K95BCWXIeQAkLwTnkepQJizPF4^bRfEQ3wCna57",
                            49, 18, 8, 3), false);
                    put(new CheckPasswordInput("ak3on8DkX1dUyKF*UOwt73eYCeTcI55i3ay^pyGEzs7a*C#9AL@Fv19tJ",
                            57, 18, 12, 7), false);
                    put(new CheckPasswordInput("7QHeHGqgf1kT_TvbV$kr",
                            20, 7, 2, 4), false);
                    put(new CheckPasswordInput("iI2l^fS^3n5vr*Oh96Wv6V0cOR^MXvU*NbxALz",
                            38, 14, 7, 5), false);
                    put(new CheckPasswordInput("a$BXsBD76w2qebVafxpZ78JA85szBuV0iBDAofEooV#BYy#NVBSHtumz*F",
                            58, 22, 6, 3), true);
                    put(new CheckPasswordInput("RQL1QjOIYSH6Ljgjft4u0zGQSr9Rgo1YmoMpkG2bC9H99tO0yg70BTkR0@iQ",
                            58, 24, 13, 0), true);
                    put(new CheckPasswordInput("^YKwM$qtZ9a_JbkQKzSe16FA%_gRyVzoBgRzI",
                            35, 14, 1, 5), true);
                    put(new CheckPasswordInput("68RaNx06eqLn$cggYD425ZCPvFYFDNmMG%Js9f9V*c4vO%JUn$j4cbl^heLDU",
                            60, 23, 9, 5), true);
                    put(new CheckPasswordInput("gxKC*H6d4cjzxFaV*MJFqs7q%",
                            25, 9, 3, 3), false);
                    put(new CheckPasswordInput("iK!VYUi#EVPLd94S0WZjv",
                            21, 9, 2, 0), true);
                    put(new CheckPasswordInput("JO!!My*O@mvC_!ePaKFxs%AZZHn0!Yboq!196%I_T",
                            41, 18, 4, 11), false);
                    put(new CheckPasswordInput("NTTtAZ7rzlUCloHNreD30WX0^n9pS*W#nvV9*86nv%iJuUGV8bG*B",
                            53, 21, 10, 6), false);
                    put(new CheckPasswordInput("jFe9D6%CxN*3@JCGJ44w$RBhSXK4_r9m6gcMwdita7TbNgeHg29m",
                            52, 15, 11, 3), true);
                    put(new CheckPasswordInput("DDfqr@XqKb@uuC2$R_h52XU7i%E@2ZXS3^ROWRnvt^ly11cZkiV1nD#jTbQvuqL",
                            62, 20, 9, 7), true);
                    put(new CheckPasswordInput("lE7oi_v$5V4Dyx*MsSDywxCjvWnUtnT_OoCA",
                            36, 13, 3, 7), false);
                    put(new CheckPasswordInput("3va6cxo%7RQA^O*IQmL5MLAdansa",
                            26, 10, 2, 2), true);
                    put(new CheckPasswordInput("taI%jZ3xgk@^X^@op@C8U",
                            21, 5, 4, 6), false);
                    put(new CheckPasswordInput("%O$^0u_4dc*wDUCuXeHmBk*vLVzG#JjEHRjR4saB%3vDQg%yO6384#3%l",
                            57, 19, 11, 11), false);
                    put(new CheckPasswordInput("O7bVQ1_UwBvTwlojrlf",
                            19, 5, 0, 1), true);
                    put(new CheckPasswordInput("8#VntT^nzKF*ExmoyP_Ha*CZO",
                            25, 8, 0, 5), true);
                    put(new CheckPasswordInput("zn$rJrYh2vMy@JIGub9M566n1Jx8UBZn",
                            32, 11, 7, 6), false);
                    put(new CheckPasswordInput("a_ufqUKHj3W!39IIqDI1Q$LO$CTUx9",
                            30, 14, 6, 4), false);
                    put(new CheckPasswordInput("FyY^v%VB0o1iS",
                            13, 5, 6, 2), false);
                    put(new CheckPasswordInput("1fyqkcA1JE8J5IK@d3appbYW3rIERYHtJ1L",
                            35, 15, 7, 5), false);
                    put(new CheckPasswordInput("!kqaFPiOqR1OOa3rmOpgiQfEiKF9uE49WZ26cSuN@0gNBROlLnM",
                            51, 22, 7, 1), true);
                    put(new CheckPasswordInput("qGB!AJWYrzKfp^MjgaxebPLRp1hCa",
                            29, 12, 2, 2), false);
                    put(new CheckPasswordInput("0GySU5N*lorjYe9gOm5Io2upT0hY5kR%wh6Ck8BMeQ2cFciXr2fxAXHY0girMT",
                            62, 22, 12, 2), true);
                    put(new CheckPasswordInput("#aB9LpIQOCfY^o2",
                            14, 7, 1, 1), true);
                    put(new CheckPasswordInput("n8gg$R!S^kO3hK_Y",
                            15, 4, 0, 4), true);
                    put(new CheckPasswordInput("SzhAjWE!A4mMPAtc*_gql9Cnl%0",
                            27, 9, 1, 3), true);
                    put(new CheckPasswordInput("nD9txy7ZxCiY_b^",
                            15, 4, 2, 3), false);
                    put(new CheckPasswordInput("z@$qMEwxeY",
                            9, 2, 0, 2), true);
                    put(new CheckPasswordInput("Hu1wLVi463K*EV7mZM",
                            18, 8, 9, 1), false);
                    put(new CheckPasswordInput("qgme9%c0IFU2EZHoVoO5Q_i7rMR63#LrZI",
                            38, 14, 7, 3), false);
                    put(new CheckPasswordInput("OIrGzeJtJfKnwCugrL!!tM^!GWX9oD236bN4CEo8wySjz0",
                            46, 15, 5, 3), true);
                    put(new CheckPasswordInput("C9z3@x6#S!JVo4*WcZlZAP@b%pUROcEgc",
                            31, 13, 2, 6), true);
                    put(new CheckPasswordInput("i2HptZVv2Ck1Q*BAoJ3vRuO5FdhG",
                            27, 10, 4, 1), true);
                    put(new CheckPasswordInput("I41J*wao",
                            8, 5, 2, 1), false);
                    put(new CheckPasswordInput("^FF32%_gZ5",
                            9, 2, 1, 2), true);
                    put(new CheckPasswordInput("AA#k8r5v*JUVepIxi0Hg#arI1@fyOEARLP%G3Ih2I9ZZQSjXowp",
                            54, 22, 7, 5), false);
                    put(new CheckPasswordInput("tXIVk@zGD6sK!D79nPIe5#*nDxbdCNdycv5*xUBEj%",
                            41, 15, 3, 6), true);
                    put(new CheckPasswordInput("itQC!1!9%Xh2FdUWSBqv5CQrtOL#!NFfldETlgQfP7DyziM1_4Nw@zS",
                            53, 20, 5, 6), true);
                    put(new CheckPasswordInput("qvUaarUw_*BQtIvOl4g@Saq8",
                            24, 7, 2, 4), false);
                    put(new CheckPasswordInput("Od87W3$^AyfyAD5y*$hTdHpa7eNyZj9d70Z",
                            33, 8, 6, 2), true);
                    put(new CheckPasswordInput("Dvv6w4YZ*raWagOqcMI6N",
                            21, 8, 5, 1), false);
                    put(new CheckPasswordInput("0%CPq5qKx5YPplyaUOVpOOEZ34Ed7Z74LO0",
                            33, 16, 7, 0), true);
                    put(new CheckPasswordInput("6q@BPZvic2#9T_74*%OiNZCKkz3vgaV%",
                            32, 12, 6, 6), false);
                    put(new CheckPasswordInput("ij1%VCm@go9UD@^aDbnniVY*UKIkb983D7#xUKFp_N5kE*29Uyo_jpyFefu",
                            57, 16, 8, 9), true);
                    put(new CheckPasswordInput("lUSggK8G1eIZifji^hnEH_iEkUXl",
                            28, 11, 2, 5), false);
                    put(new CheckPasswordInput("u6L%!@j*txbQ#Gdk09y8!Yx6VP8*0vIn",
                            31, 6, 7, 6), true);
                    put(new CheckPasswordInput("hF!Px^qmLRbUofawalmUIV9XQ7D9U5tSLW!84poICmAd",
                            42, 18, 6, 2), true);
                    put(new CheckPasswordInput("T102q$vWQZZ1",
                            10, 4, 4, 0), true);
                    put(new CheckPasswordInput("x7X*xTo%!pc3zhrfJ#J3RA9ClYR*m%p9hbe2Hd2_6nH",
                            42, 10, 6, 5), true);
                    put(new CheckPasswordInput("^o#%*Lrlie8D%^NA6tI",
                            17, 5, 1, 5), true);
                    put(new CheckPasswordInput("qcxv0A!sLZpURFyw1Y",
                            18, 7, 2, 5), false);
                    put(new CheckPasswordInput("toKM4AgleiY9kr61s1pP11#Fmlig8q^b6%XkIt0xwL%tq65FiLZl",
                            52, 12, 16, 4), false);
                    put(new CheckPasswordInput("Qkh*31@Ka9!_wiverLbpP0iCXqXqA8nX*Xj308vuA^",
                            42, 11, 9, 6), false);
                    put(new CheckPasswordInput("k@O^W#QQuvBWvRb!^ye",
                            17, 5, 0, 5), true);
                    put(new CheckPasswordInput("jMGhjQ#z!_woGLg8e4c1Nyby8NpJD4r%RfXxsFB",
                            39, 17, 5, 4), false);
                    put(new CheckPasswordInput("#GphYZm*XRevyPGlrr7X1ICC8hyO39j9ISAJ82fXe_q03s5c^DcCNEm",
                            55, 21, 13, 4), false);
                    put(new CheckPasswordInput("d^_t2Ai_2TwAHQNKr7PRENufyerZSL*sSiQr9rkJ",
                            40, 17, 4, 7), false);
                    put(new CheckPasswordInput("cUh%2BTmqGEU%HrV#R%vwet2DR",
                            26, 11, 2, 7), false);
                    put(new CheckPasswordInput("7k6C6ElyYqb5aXXBp8SHPaTt5oVqtZYRP5uE^S0tNS15J_Z0HljHAcL",
                            57, 25, 11, 2), false);
                    put(new CheckPasswordInput("NwrDO9MvsK!nU!Twnbk$@iZA8yC@wiFnJV!!R",
                            37, 14, 4, 7), false);
                    put(new CheckPasswordInput("KuQuYrqpOclkUnGeZD*UaX$MccgRToWcZeB",
                            34, 15, 0, 1), true);
                    put(new CheckPasswordInput("1olrFH#yYhDF8@lkhukvvot_^TN",
                            31, 7, 2, 4), false);
                    put(new CheckPasswordInput("iEz2f#G#WsslKH5AWSxLxrVotoxfv3S^R5a5xswdyPcZ8k0XYeVL7@l",
                            55, 18, 12, 4), false);
                    put(new CheckPasswordInput("RTcI^A#i*fVLK0XEsj5^yu@90tkvj3MBpru",
                            34, 11, 5, 4), true);
                    put(new CheckPasswordInput("UDgxluKEHC8v67%i9KdpVInlaD8uLYcNOipDN3u#",
                            40, 15, 4, 2), true);
                    put(new CheckPasswordInput("DVO_nkj%bwWjw4TJJKtTV5m87JdS!nkBFQei$K^MV1MCHjTSR5PABfi_P*CF",
                            58, 30, 4, 6), true);
                    put(new CheckPasswordInput("qLKLqV5fMm0w!o8pxu0MQ@!RJ19YI0Lu9pbxayJAimV^YRmHbW8T0L_yeVq",
                            59, 25, 10, 5), false);
                    put(new CheckPasswordInput("*%E9mfcxCUl1wRROdSWlL",
                            21, 9, 0, 0), true);
                    put(new CheckPasswordInput("UmUlpjfrk*!PJzVDi7%5K",
                            25, 7, 2, 3), false);
                    put(new CheckPasswordInput("YSxZ%b0vaECPQ^egUJ@klveFfy6YDOmeK6ayvNgird^EP#P74u_a",
                            52, 18, 3, 5), true);
                    put(new CheckPasswordInput("bUIbDKWBJm^02NFmN#v5JKqP!4Y%gG1",
                            31, 15, 5, 8), false);
                    put(new CheckPasswordInput("SzmfJJbTBkeTxaEeAv5Uyq*j^_4itlTWDop^PBusB2IU1J4LTXTv%Uq^^%Nr",
                            60, 25, 5, 8), false);
                    put(new CheckPasswordInput("JCIGU2fCW3uu6a_sxs8di3VP1Wip_GRU3NZCuY3Y79I",
                            43, 19, 10, 5), false);
                    put(new CheckPasswordInput("Rbnyd5**^!Eliu7eUOP%AWOUGKF7xunpqonwQa*xEg^^W93_Vm8",
                            51, 15, 5, 7), true);
                    put(new CheckPasswordInput("ETljq%lpnqSVyn!6XWUnQ2",
                            26, 8, 2, 2), false);
                    put(new CheckPasswordInput("%VNv3WR7BZOQbCw4L_1AVVTpoa4Us*hgmtV7eAkd9vT",
                            44, 18, 7, 3), false);
                    put(new CheckPasswordInput("TZYT_Rpt*9Mv5Ll$90Cr5a$$56Cx4ndr^D35nJg",
                            42, 11, 10, 6), false);
                    put(new CheckPasswordInput("a0Ukd#@XsKKcjLJX1GmFnRcHX!SM7urck4pcpuqc7tJDaJKTtXSXCk$FfaR6BW",
                            61, 27, 6, 2), true);
                    put(new CheckPasswordInput("imadWsF#v*Il3DyjZXpcdx2pi0aWr",
                            29, 7, 3, 6), false);
                    put(new CheckPasswordInput("7YYJ34MqB7ZQrEyiVpWEV^1ktuqMhtdiIfDRNrc$caz1JK*9ZB",
                            50, 22, 7, 3), false);
                    put(new CheckPasswordInput("KD##%77m1NR34nAmCdy",
                            19, 10, 5, 3), false);
                    put(new CheckPasswordInput("65z9h@!QQDicA%bUNE",
                            18, 9, 3, 3), false);
                    put(new CheckPasswordInput("8r6!swOWQNxr_Jjn6WeNIakw6zG",
                            26, 7, 3, 0), true);
                    put(new CheckPasswordInput("MUgK2*#0W%EynsRZZ",
                            17, 8, 5, 3), false);
                    put(new CheckPasswordInput("*IP8H71y_EjONVetze#3ZE262SPpyTncFETK9Uy2Vb@srL7!F%E",
                            51, 21, 12, 6), false);
                    put(new CheckPasswordInput("D6qiOxjRbQsNqcXKjIfJP3d%yqCrK8wxI$avJz7#uM",
                            42, 14, 2, 2), true);
                    put(new CheckPasswordInput("BkH@o2F1BP",
                            10, 9, 2, 1), false);
                    put(new CheckPasswordInput("KUE@@w1@xYwh",
                            12, 4, 1, 6), false);
                    put(new CheckPasswordInput("JPORWn#Zhw93RRYq$oBB2cxI!",
                            24, 12, 1, 2), true);
                    put(new CheckPasswordInput("tac^*Igi5Aqw^2gtGdetXUa",
                            23, 5, 4, 3), false);
                    put(new CheckPasswordInput("2NXFarOEkE0n4Mqa79NZmXhU",
                            24, 10, 3, 0), true);
                    put(new CheckPasswordInput("3B06WdI$MRhimgOOd!gsL6azhD#^NHHaPhBsKX7SDPuhs_",
                            46, 23, 5, 5), false);
                    put(new CheckPasswordInput("UXETMvRq321HkRLQ@iALKlBAcTwmvwv8$Ie5TqrT",
                            40, 22, 5, 2), false);
                    put(new CheckPasswordInput("Zh!pBwbBRY*8o",
                            13, 5, 1, 3), false);
                    put(new CheckPasswordInput("C5s_hGVivyprKGqh*U",
                            18, 6, 1, 1), true);
                    put(new CheckPasswordInput("1zUGog_OIr9AegFvHGSbSiBFMpkde2yo%k6a#cSE2M7HbPO3rdlNqJPl",
                            56, 24, 7, 3), false);
                    put(new CheckPasswordInput("pkgg@Tx#r!@!ki3q#VP5$B3j_v4SF!fg5Om5*SCm5kIgPW92vQfhc3qi4",
                            57, 15, 11, 10), false);
                    put(new CheckPasswordInput("MP2*JVD^AOle8d0CEmgJGg@hFQAHgf",
                            28, 14, 2, 2), true);
                    put(new CheckPasswordInput("2OQVjjmXturw*GNkL$aTjWZOIP%kRe5LMCcUNqg^C6A",
                            43, 22, 3, 4), false);
                    put(new CheckPasswordInput("DRAwH3yrt^iGok8pC1TCYd#_BTg^u@$mH9AkQaJMeXvKVmg",
                            47, 19, 6, 6), false);
                    put(new CheckPasswordInput("bS7^koB2MK6gft!lZ8z08HjJFL5HE*ARx4cZe_N^O_4u",
                            44, 15, 7, 4), true);
                    put(new CheckPasswordInput("K51F!fob%3ID^Yu_1EVp59afXpJ",
                            25, 9, 4, 3), true);
                    put(new CheckPasswordInput("oByKogo8TMAFj#0uZ8BIcpzVvxB6s*MKJkCcM%zbKWwFC%ujrd7zH0Y9",
                            55, 22, 6, 3), true);
                    put(new CheckPasswordInput("FTl77PvGVAH5COWBOxD7oiuMG5Stf$*$1zpA",
                            39, 17, 6, 3), false);
                    put(new CheckPasswordInput("IJVkxrO%J*R!UHS1k3$7zUnrraEd$JjJCm6BsL6A^CKSDqhdYQ",
                            50, 27, 5, 6), false);
                    put(new CheckPasswordInput("jQcNFYlf6bgoIBoR0t5k29Rz$eZ80rg5RRSUb_VyMBZA0",
                            45, 18, 12, 2), false);
                    put(new CheckPasswordInput("z1r*cDnS2RZE@hsRjbIkoFP",
                            21, 8, 0, 0), true);
                    put(new CheckPasswordInput("JA9_i$CIgTZB3O41wWiM",
                            20, 9, 2, 1), true);
                    put(new CheckPasswordInput("GIz3VZ0zdL$SEV!zI$DW9c0mX42tnPwrF!UIvfaG!H",
                            42, 18, 9, 5), false);
                    put(new CheckPasswordInput("*37K$BDaO_OeR",
                            14, 6, 2, 3), false);
                    put(new CheckPasswordInput("by^8^HhC38fZVhRtMals47lvm3GGIWI8b7Xj2tWgQG9oi$",
                            44, 13, 10, 3), true);
                    put(new CheckPasswordInput("__nRIg0rcY#JHUpxUj5h54Mx#@%Qjmrn5axG",
                            36, 10, 5, 8), false);
                    put(new CheckPasswordInput("z#NRd1JG!92MuVG_^bVEDHqoJkk%bh9R0Um@CD4T",
                            40, 17, 7, 6), false);
                    put(new CheckPasswordInput("*#wPZEM#J2#l_2JbR3QAx4J!sE$7n9L3$uVLbON8c9Acjs3Hre@q",
                            56, 18, 10, 9), false);
                    put(new CheckPasswordInput("%^Y2An2OTtJr",
                            15, 5, 2, 2), false);
                    put(new CheckPasswordInput("scVmPk6UPuFUSHJi%38",
                            19, 10, 3, 1), false);
                    put(new CheckPasswordInput("Dz6MKY4JgQOOk346!MOUFXcLMICSN^#%XN$dB$cNu",
                            39, 23, 3, 5), true);
                    put(new CheckPasswordInput("%dlzKJ0GkdTi__$z28*hIxS0lR9XeEshMq2iVkIej_u5n2^*%587Gw@Jysy",
                            58, 13, 10, 8), true);
                    put(new CheckPasswordInput("HOt*BGW6yT0nTcn^9H9Qy7",
                            22, 7, 5, 1), true);
                    put(new CheckPasswordInput("r35rz5wA8WS7YjWTIqbXikxGJ",
                            23, 9, 4, 0), true);
                    put(new CheckPasswordInput("fDDXVzdtI^doul0vyDjsI$wtJVr3SaW3mFycN",
                            37, 11, 1, 0), true);
                    put(new CheckPasswordInput("X7wwz09Rp97NaW^ahMfay0Ck3z#y0",
                            29, 7, 8, 2), false);
                    put(new CheckPasswordInput("5H7KsS*2yvVsPYm0T%v$VK0h$%SgPJ*3ihoHC$J7^TeeH",
                            44, 17, 7, 7), true);
                    put(new CheckPasswordInput("xqQhLOrHpDbGd%A@d^RPJ^vpt5yOLc@SSyyi0JA5QxdwRMN",
                            49, 20, 3, 5), false);
                    put(new CheckPasswordInput("*eejk_cm#ERCuscDq5qAA1Qj2xitF",
                            29, 8, 3, 6), false);
                    put(new CheckPasswordInput("*O$iIr^EOh#%ofesm",
                            17, 4, 0, 8), false);
                    put(new CheckPasswordInput("S^^XrWhPlx2s9eNNtBiwByhm405Dq8qt0B$r",
                            36, 10, 10, 3), false);
                    put(new CheckPasswordInput("l#W5t4tNPvU7HdiI8fzOvM4@QndN_Ex3lwo$2HQ12U",
                            45, 14, 9, 4), false);
                    put(new CheckPasswordInput("hl04ok2p47mjTKEY1YzyOPtgrPTObndsWyeDsd##tWK2GM1A#H",
                            50, 22, 8, 3), false);
                    put(new CheckPasswordInput("2^!QUIZBE1uhD!Ena85VsqA",
                            23, 14, 4, 3), false);
                    put(new CheckPasswordInput("vRDdmxwBnwAy1$@1!oZ4cMqkAMYB6s6ZmqZcjHJHEZf!VskRG",
                            47, 19, 3, 3), true);
                    put(new CheckPasswordInput("RaHby%f9!A_ELyYKOEC2",
                            20, 10, 0, 2), true);
                    put(new CheckPasswordInput("RGnNyS@qKcxmZNxxPMjWN90dj4Ciljk%joaFpt4CpRVkNUfcbAdX1OYr",
                            56, 22, 8, 2), false);
                    put(new CheckPasswordInput("cA5tKXk!BZKX7DMQGva2h2*e%WukEZWqNrv9^Jbb2",
                            40, 15, 4, 3), true);
                    put(new CheckPasswordInput("1lqsQHMBdORk11z^twcFqx$U8#www_OO@hAf3wjfkrW#EBLeqeO",
                            51, 15, 5, 6), true);
                    put(new CheckPasswordInput("ziGs92F_3FblKawUUuvhbqefj_iBm0MW$WiFLVqBZ5I",
                            43, 17, 5, 3), false);
                    put(new CheckPasswordInput("tynjbn@wRpsIQqNwIt_5hdJT#B3zinN",
                            29, 7, 2, 1), true);
                    put(new CheckPasswordInput("4RjB!K1#UlVWZTk",
                            15, 12, 2, 2), false);
                    put(new CheckPasswordInput("N@fW^*aQmPp",
                            11, 4, 0, 5), false);
                    put(new CheckPasswordInput("4R@%ln5o",
                            8, 1, 3, 2), false);
                    put(new CheckPasswordInput("uvKdzts@PsFL@%eSLcNXBtirf%WU^KFCx*kfHRo!1DruaN$o",
                            46, 16, 0, 6), true);
                    put(new CheckPasswordInput("GRDr6_Jvnc!",
                            11, 6, 1, 2), false);
                    put(new CheckPasswordInput("I$eGJlckr30",
                            11, 3, 4, 1), false);
                    put(new CheckPasswordInput("EQQs_vt5EX7XoRIaX*e!fwD^V@bhcE80*%K!6W6DLBiQuo91LiYcD$",
                            54, 20, 7, 9), true);
                    put(new CheckPasswordInput("$o3xGtguz_3fXwLG",
                            16, 2, 1, 0), true);
                    put(new CheckPasswordInput("ev!2CFZUkC@mDMrQT8O^!v",
                            22, 8, 2, 4), true);
                    put(new CheckPasswordInput("Cho1zTs4C@jrfomB3RJ5fpKAx@r%DPaed3lWByZqNbiUE^hPO_8SJK",
                            54, 19, 4, 5), true);
                    put(new CheckPasswordInput("%mwi@s9QDDIiDlOcQYgv_J!Mt@amETWeHIbv5I_*!t9qRPPoRjn#3KE",
                            53, 20, 2, 9), true);
                    put(new CheckPasswordInput("cKEXzap9^nM9GSC%0TmRkEsdmZO$tsJS_UWjk#y#2N#9XZt^MP@",
                            51, 20, 3, 7), true);
                    put(new CheckPasswordInput("O96S4#92vSORHM7k1F5UVen1j$$gXgsjcC6_FFA76jT^4oz*#",
                            50, 16, 13, 7), false);
                    put(new CheckPasswordInput("8_QGSwfS9QTAplpNOhJtgWFGDBYSe%aw8a",
                            36, 17, 3, 2), false);
                    put(new CheckPasswordInput("TqEjmzrCiEdC",
                            15, 5, 0, 0), false);
                    put(new CheckPasswordInput("Kc7B8jvdqv9TG^mM*w1exTHY9O0Bk%BBYePygq_C%fsUah$",
                            51, 16, 6, 6), false);
                    put(new CheckPasswordInput("FNqn1R_GPPpzcm9BoJ58_kis84_LSEMhG5vC8*vjUL9X@c!@qaN",
                            52, 18, 9, 7), false);
                    put(new CheckPasswordInput("StoYgLxBSpAW0%eejtma6G97G3o9jOoZRU6_od0e19jZ2tczdYAb2Eor!4jFxY",
                            65, 19, 13, 3), false);
                    put(new CheckPasswordInput("uuimoOJ18S0$x!KjmmrH1eKx4$0RZl$",
                            30, 8, 5, 3), true);
                    put(new CheckPasswordInput("4L2RPllVhg_mg$_6143LOd1wuH#$73ZiTsOmx*U8bTTpqWqUVjvdmXVFDUJR",
                            60, 23, 11, 6), false);
                    put(new CheckPasswordInput("D7SVN*#g",
                            6, 4, 1, 1), true);
                    put(new CheckPasswordInput("qteSjXy%v2I100ymd7f2#HFe3zhuQBF!Gn#b4Dj3$$k!d@zNX!uBnol",
                            57, 13, 9, 9), false);
                    put(new CheckPasswordInput("h#EZ2C2aFYlOnEt43o9!^XM^D#bq9",
                            29, 10, 6, 7), false);
                    put(new CheckPasswordInput("O%m%FpIgi0$Q#%5EAp#LV3^qUS",
                            26, 10, 3, 10), false);
                    put(new CheckPasswordInput("q2kwg2D#xpgNXWkZcDa1XLReigfVZZ3mzhEn80VPLsf",
                            41, 15, 6, 0), true);
                    put(new CheckPasswordInput("s$!tshX_AOlKsRfVxVN3yE$z$6qBzY",
                            29, 10, 0, 3), true);
                    put(new CheckPasswordInput("_Z6c_Ur6Fge2zwPO3yiqouWEWM%h@",
                            30, 9, 4, 4), false);
                    put(new CheckPasswordInput("1i5^j6bjno#K8$!J_V!T1OiGHypRTPtGB!ewGzxYg5sWeJbQP^Qh9S0pXT_x_",
                            61, 24, 8, 10), false);
                    put(new CheckPasswordInput("eYmwoa#tnC^",
                            11, 2, 4, 2), false);
                    put(new CheckPasswordInput("s6%QMAoHcOl@waUctHPX3!",
                            23, 9, 2, 3), false);
                    put(new CheckPasswordInput("lGX4aFzFliITJTmJFEXvWNkwoHJQU8EvUmCi",
                            34, 19, 1, 0), true);
                    put(new CheckPasswordInput("@i88gohPet4ulUEXwaE%Hjm1D*G6rA6n!^m1ieIH*ZWg^l",
                            46, 15, 7, 7), false);
                    put(new CheckPasswordInput("v#TE9kq5",
                            7, 0, 1, 1), true);
                    put(new CheckPasswordInput("n*bX^kehNAF^ajMvSYeU%5nRkAq@@ZY!FLJ",
                            35, 15, 1, 10), false);
                    put(new CheckPasswordInput("yHM4JjueEO!9SpPDgLn94arBN3Dgr@Mt2ILeb2txfSM$^D4W%C6",
                            49, 19, 8, 3), true);
                    put(new CheckPasswordInput("LgEgI!NssNY!0rfvmABCKxwGJy4Y61c2^P7",
                            35, 14, 6, 4), false);
                    put(new CheckPasswordInput("G!Aajvf!tyYNa2HU6",
                            17, 5, 0, 0), true);
                    put(new CheckPasswordInput("e%JaIFkbUz67iMs9hA9Bm4vxOCKjm19Ftd*rBt%2nskeOlxPfv6",
                            50, 13, 9, 1), true);
                    put(new CheckPasswordInput("lIn3Fg4LJU!fbRQ37tOH",
                            18, 8, 4, 0), true);
                    put(new CheckPasswordInput("N6%ZPVnAiy*y",
                            12, 5, 1, 5), false);
                    put(new CheckPasswordInput("Z_W%*8HCd%^tL8S",
                            18, 6, 2, 5), false);
                    put(new CheckPasswordInput("d3@rnfoRe1slkiZUJA3IRdGA",
                            24, 7, 3, 0), true);
                    put(new CheckPasswordInput("30z_Nap!%eP8XJZB@zc7v1YWv3UDT0D^23xf*#YdzgJQt^J",
                            47, 16, 12, 8), false);
                    put(new CheckPasswordInput("Z8_b@mf5vBs$B3yV1G5qCmLvL6g^CBtw#aX1oua8KX",
                            40, 11, 8, 3), true);
                    put(new CheckPasswordInput("P8VnEybR5T6TdDea3f@qrN#poEIFuVZqW9RP8Cp@3pHn4",
                            45, 18, 8, 6), false);
                    put(new CheckPasswordInput("YdvR3QmNK^3R_tcBcqRS8hYGS62BxJ9p2NqYnT8ZH9QyAnTLHv_9_ohpIWyuB@q",
                            63, 27, 14, 5), false);
                    put(new CheckPasswordInput("Y*FetvUSt63LmkOTWb_@lgg6psw",
                            27, 6, 2, 3), true);
                    put(new CheckPasswordInput("Lf$gYdTpTTQW_5",
                            14, 5, 0, 0), true);
                    put(new CheckPasswordInput("1gk1nw3R58X15inim0jW#i",
                            22, 1, 7, 0), true);
                    put(new CheckPasswordInput("8LQ4jG2OYHawrj4V75aRiKOn@1qh6LjkTMYJNHC6o*cW1$o5nvQGjZ%Z!hEe",
                            60, 24, 13, 5), false);
                    put(new CheckPasswordInput("MPPSaF0ujBC7gxvink3s#6*ZWk%Rgx8xdiofspsY1",
                            41, 9, 5, 3), true);
                    put(new CheckPasswordInput("A$!W%4uS5qUcu5Mdn*",
                            16, 5, 2, 3), true);
                    put(new CheckPasswordInput("ck%e*2BDudkI#Tq4l^cxYEr",
                            23, 5, 0, 2), true);
                    put(new CheckPasswordInput("zo5T#^Lld^vu60URMmR0#Jru_Y",
                            26, 9, 4, 5), false);
                    put(new CheckPasswordInput("pG5oZ05VP8srvls_vW7sL@ZEwC@Op",
                            29, 12, 5, 3), false);
                    put(new CheckPasswordInput("QoBPESuYeoa0X5_@puji4AD",
                            23, 9, 2, 0), true);
                    put(new CheckPasswordInput("%t8ciZpDhI6dIfo27k74$yRYj8vhaK4",
                            31, 6, 8, 0), true);
                    put(new CheckPasswordInput("vnq$uZCPKDboYr5_SJ1Wqg9alXIC1D7OF%0oI2dMNhCJ9Xr5nWa5P%LN%FHazY",
                            62, 32, 10, 5), false);
                    put(new CheckPasswordInput("0tr#8#3H*hO^!yLgke0T7qy*X78^E1",
                            30, 6, 7, 5), true);
                    put(new CheckPasswordInput("P8^$m635uBVlw@NYx@Z4T%t4Hi16t347KxmnPyYSFP0nJ7$uhW_GN$UE",
                            57, 20, 13, 8), false);
                    put(new CheckPasswordInput("oIDOofOgvz#Gk!H8B%KqB793RWvJBjYZG!*MnOyx7lyh4Zto7pUXnBR#eKB",
                            58, 25, 5, 6), true);
                    put(new CheckPasswordInput("qelYj$eHFGeq%rR^L_m",
                            19, 6, 0, 7), false);
                    put(new CheckPasswordInput("GBzuEk6hFau8tFsY!Ek@wvqzZsq%q159BvuSm!P#EB",
                            42, 12, 3, 3), true);
                    put(new CheckPasswordInput("Qhjri0iGXLaIvP*Ep",
                            17, 7, 1, 2), false);
                    put(new CheckPasswordInput("J1Jd5Iuhkrr7#hMoCSx5jj0_C_V!tqv",
                            29, 7, 4, 4), true);
                    put(new CheckPasswordInput("A0vz%WSIOh*KZrq27OcBF2%J3KMB1cDFPrNQS%dPb9aQw",
                            47, 22, 7, 4), false);
                    put(new CheckPasswordInput("51HUyzqENC5T0NYKQ",
                            16, 8, 2, 0), true);
                    put(new CheckPasswordInput("hfyldh5b5@gzDQwE!SuPRQJ^U3$_8#",
                            30, 9, 7, 6), false);
                    put(new CheckPasswordInput("qOcW@^J0",
                            8, 2, 1, 2), true);
                    put(new CheckPasswordInput("wj90C6CTrHxsqJXx4Vnjk!94DFeXQlP!R",
                            32, 11, 4, 0), true);
                    put(new CheckPasswordInput("OkWG8uaNIP!*3G3TDYhs",
                            21, 10, 3, 2), false);
                    put(new CheckPasswordInput("7l4w_wQ_6zSl04",
                            14, 2, 5, 4), false);
                    put(new CheckPasswordInput("6hHhPxwgM9$j@KV8Pai1f#ef8G8$#D*V1^bsv!0AQ1w$vhmVaGT$H",
                            52, 15, 7, 8), true);
                    put(new CheckPasswordInput("m^CA*KIY1B7yk_b_TDl^yCd8QuwG$v5OUDhYWAvP77SFcuqwFqs",
                            51, 21, 10, 6), false);
                    put(new CheckPasswordInput("$a9*Yu2r*JovhC*s_c6qSG1MK3^@rG4hC52jl5MBPbv",
                            42, 12, 9, 6), true);
                    put(new CheckPasswordInput("enxClz_GsNYW%z2c6sM",
                            21, 6, 2, 2), false);
                    put(new CheckPasswordInput("6dl^*E1Jc@#Z$pXRHGYQk_s5pdQeXcTym!S!PofElXj*LZ%ri^jJt1B_",
                            56, 19, 2, 10), true);
                    put(new CheckPasswordInput("#2h0vqXsjT$Cw3$1W*gOilDOaBvp^w@Plbs*R^*GszX",
                            42, 12, 2, 7), true);
                    put(new CheckPasswordInput("N7j56rqSOd0xaBSHlh_8DOWfL#!6nJh",
                            31, 10, 6, 2), true);
                    put(new CheckPasswordInput("ptYq8S!mFsXv29rW",
                            16, 5, 4, 1), false);
                    put(new CheckPasswordInput("geM_3pXNrXh_b%8wSGOu6m25zM%tTYfdc56b$L$%kMQpcNT76DYx1OtFtcoTft",
                            61, 19, 8, 6), true);
                    put(new CheckPasswordInput("r6XeOak1cO2r8#p",
                            18, 3, 4, 1), false);
                    put(new CheckPasswordInput("d#PVY9nqRPsJuaT#J!O1ieDFJ!YH%t7KCx#HaxC_tsgRoEk!xNtz2",
                            53, 22, 4, 8), false);
                    put(new CheckPasswordInput("XfjSbM*84iX6!p0w_zRmKeQOrKa6JuwT@8xX8x0^HK#SE",
                            45, 15, 8, 5), true);
                    put(new CheckPasswordInput("lcYeIKu3xR%SBi0px%A63jd#gSGPokB2QSaoEcV7pPY4SbERZjGavLj85B$^0Dfc",
                            64, 25, 10, 4), true);
                    put(new CheckPasswordInput("Ou^qrWhWbdo_TCinsc7JgGrwTdD7Yo",
                            29, 8, 1, 2), true);
                    put(new CheckPasswordInput("iLIY*0MFnqggSzjjc%cTN8C_S^_lR1TK$a%K",
                            35, 13, 1, 7), true);
                    put(new CheckPasswordInput("L5YxBaGytUlCSpfwfvy6CqBw*J*1JwlPF7XLhgvnlwIA%I$",
                            47, 18, 5, 4), false);
                    put(new CheckPasswordInput("EzZv!2WRICN7A@e6bP9#qL5dy9q#PjX3yOPEnK#@2zZJpIHB9g8_cPF#RU6",
                            60, 25, 11, 8), false);
                    put(new CheckPasswordInput("6ip_UkfB^t!Yh$42FbCLx$Pb*IqV@qmTea$",
                            33, 9, 2, 6), true);
                    put(new CheckPasswordInput("FK3CjeOzK7hdv253xOYnd*C0g#jt%S3aw%CQjG5nc4gQJa",
                            46, 16, 9, 4), false);
                    put(new CheckPasswordInput("!0Jfc1QmBQ%4N3pQB^jaC!Adql%OLXSiq%846mH30",
                            39, 14, 9, 5), true);
                    put(new CheckPasswordInput("4WA0Vum#Gn",
                            10, 2, 1, 1), true);
                    put(new CheckPasswordInput("fg0DI1RsTz_HJV6s9^B5AWk1u7Pa5UTXCIOt_Ff5LNoLy@xm#zjNK7gW",
                            57, 24, 10, 5), false);
                    put(new CheckPasswordInput("R^Dsaq%o8w!HRjN#h#6@Fm7rdRV7N^c$",
                            34, 9, 4, 8), false);
                    put(new CheckPasswordInput("SmlP1LBuf2RuE*fT$IykDLEvt69oe9_W4t24oVoAm0A0sIal$OU@J$c4",
                            55, 19, 10, 5), true);
                    put(new CheckPasswordInput("5ezy^EY5KUtnZKfF^blkckhBgY%LmHpUp^d",
                            39, 12, 2, 4), false);
                    /* END AUTOGENERATED CODE */
                }
            };
}
